//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BowlingService.Business
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class game
    {
        public game()
        {
            this.players = new HashSet<player>();
            this.turns = new HashSet<turn>();
        }

        [DataMember]
        public int Id { get; set; }

        [DataMember]
        public Nullable<int> Lane_id { get; set; }

        [DataMember]
        public string State { get; set; }

        [DataMember]
        public Nullable<System.DateTime> Created_at { get; set; }

        [DataMember]
        public virtual lane lane { get; set; }

        [DataMember]
        public virtual ICollection<player> players { get; set; }

        [DataMember]
        public virtual ICollection<turn> turns { get; set; }
    }
}
