//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BowlingService.Business
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

  //  [Serializable]
    [DataContract]
    public partial class player
    {
        public player()
        {
            this.turns = new HashSet<turn>();
        }

        [DataMember]
        public int Id { get; set; }

        [DataMember]
        public Nullable<int> Game_id { get; set; }

        [DataMember]
        public string Pseudo { get; set; }

        [DataMember]
        public string Password { get; set; }

        [DataMember]
        public virtual game game { get; set; }

        [DataMember]
        public virtual ICollection<turn> turns { get; set; }
    }
}
