//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BowlingService.Business
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class @throw
    {
        [DataMember]
        public int Id { get; set; }

        [DataMember]
        public Nullable<int> Turn_id { get; set; }

        [DataMember]
        public Nullable<int> Fallen_skittles { get; set; }

        [DataMember]
        public Nullable<int> number { get; set; }

        [DataMember]
        public virtual turn turn { get; set; }
    }
}
