//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BowlingService.Business
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class lane
    {
        public lane()
        {
            this.games = new HashSet<game>();
        }

        [DataMember]
        public int Id { get; set; }

        [DataMember]
        public string State { get; set; }

        [DataMember]
        public virtual ICollection<game> games { get; set; }
    }
}
